### ISSUE TITLE
Can't see the HTTPS portal in the settings

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#309] opened 2021-07-05 14:08 UTC
As expected, when I go to the Networking section of settings, it prompts me to download the HTTPS portal

<img width="1283" alt="Screenshot 2021-07-05 at 16 06 33" src="https://user-images.githubusercontent.com/19168735/124483773-005a5c00-ddab-11eb-86b2-29b157bf6376.png">

But when I click on it to try to download, it starts installing...
<img width="1284" alt="Screenshot 2021-07-05 at 16 07 36" src="https://user-images.githubusercontent.com/19168735/124483901-2122b180-ddab-11eb-8707-970b3c05ca88.png">

But then it runs into the following error:
```
errorCall to packageInstall
Today, 0 min ago
Reply: Command failed: docker-compose -f /usr/src/app/DNCORE/docker-compose-https.yml up --detach <&- Found orphan containers (DAppNodeCore-vpn.dnp.dappnode.eth, DAppNodeCore-wifi.dnp.dappnode.eth, DAppNodeCore-core.dnp.dappnode.eth, DAppNodeCore-dappmanager.dnp.dappnode.eth, DAppNodeCore-ipfs.dnp.dappnode.eth, DAppNodeCore-bind.dnp.dappnode.eth) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. Starting DAppNodeCore-https.dnp.dappnode.eth ... Host is already in use by another container [1A[2K Starting DAppNodeCore-https.dnp.dappnode.eth ... [31merror[0m [1B ERROR: for DAppNodeCore-https.dnp.dappnode.eth Cannot start service https.dnp.dappnode.eth: driver failed programming external connectivity on endpoint DAppNodeCore-https.dnp.dappnode.eth (88c9a7a1bb522c7b9ef1aab7130bbc21c8d70296dc172aba67b1fab61fb9c72b): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use ERROR: for https.dnp.dappnode.eth Cannot start service https.dnp.dappnode.eth: driver failed programming external connectivity on endpoint DAppNodeCore-https.dnp.dappnode.eth (88c9a7a1bb522c7b9ef1aab7130bbc21c8d70296dc172aba67b1fab61fb9c72b): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use Encountered errors while bringing up the project.

error23Call to httpsPortalExposableServicesGet
Today, 0 min ago
Reply: request to http://https.dappnode:5000/?format=json failed, reason: getaddrinfo ENOTFOUND https.dappnode

```

**Comment by dapplion** [comment] 2021-07-06 18:32
Damn, the super long docker errors, will be easier to read like this:

> Reply: Command failed: docker-compose -f /usr/src/app/DNCORE/docker-compose-https.yml up --detach <&- Found orphan containers (DAppNodeCore-vpn.dnp.dappnode.eth, DAppNodeCore-wifi.dnp.dappnode.eth, DAppNodeCore-core.dnp.dappnode.eth, DAppNodeCore-dappmanager.dnp.dappnode.eth, DAppNodeCore-ipfs.dnp.dappnode.eth, DAppNodeCore-bind.dnp.dappnode.eth) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. Starting DAppNodeCore-https.dnp.dappnode.eth ... Host is already in use by another container �[1A�[2K Starting DAppNodeCore-https.dnp.dappnode.eth ... �[31merror�[0m �[1B ERROR: for DAppNodeCore-https.dnp.dappnode.eth Cannot start service https.dnp.dappnode.eth: driver failed programming external connectivity on endpoint DAppNodeCore-https.dnp.dappnode.eth (88c9a7a1bb522c7b9ef1aab7130bbc21c8d70296dc172aba67b1fab61fb9c72b): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use ERROR: for https.dnp.dappnode.eth Cannot start service https.dnp.dappnode.eth: driver failed programming external connectivity on endpoint DAppNodeCore-https.dnp.dappnode.eth (88c9a7a1bb522c7b9ef1aab7130bbc21c8d70296dc172aba67b1fab61fb9c72b): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use Encountered errors while bringing up the project.

The issue is that another process is already using the port 80. 

```
0.0.0.0:80: bind: address already in use ERROR:
```

@pablomendezroyo Can you help debug which service is binding that port already? Could there be duplicate https instances?

**Comment by pablomendezroyo** [comment] 2021-07-07 07:49
> Damn, the super long docker errors, will be easier to read like this:
> 
> > Reply: Command failed: docker-compose -f /usr/src/app/DNCORE/docker-compose-https.yml up --detach <&- Found orphan containers (DAppNodeCore-vpn.dnp.dappnode.eth, DAppNodeCore-wifi.dnp.dappnode.eth, DAppNodeCore-core.dnp.dappnode.eth, DAppNodeCore-dappmanager.dnp.dappnode.eth, DAppNodeCore-ipfs.dnp.dappnode.eth, DAppNodeCore-bind.dnp.dappnode.eth) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. Starting DAppNodeCore-https.dnp.dappnode.eth ... Host is already in use by another container �[1A�[2K Starting DAppNodeCore-https.dnp.dappnode.eth ... �[31merror�[0m �[1B ERROR: for DAppNodeCore-https.dnp.dappnode.eth Cannot start service https.dnp.dappnode.eth: driver failed programming external connectivity on endpoint DAppNodeCore-https.dnp.dappnode.eth (88c9a7a1bb522c7b9ef1aab7130bbc21c8d70296dc172aba67b1fab61fb9c72b): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use ERROR: for https.dnp.dappnode.eth Cannot start service https.dnp.dappnode.eth: driver failed programming external connectivity on endpoint DAppNodeCore-https.dnp.dappnode.eth (88c9a7a1bb522c7b9ef1aab7130bbc21c8d70296dc172aba67b1fab61fb9c72b): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use Encountered errors while bringing up the project.
> 
> The issue is that another process is already using the port 80.
> 
> ```
> 0.0.0.0:80: bind: address already in use ERROR:
> ```
> 
> @pablomendezroyo Can you help debug which service is binding that port already? Could there be duplicate https instances?
@Pol-Lanski 
- Check it from the dappmanager UI:
An easy check is going to **support > ports** section and scan ports to see if any application from dappnode is using those ports. But probable is not from dappnode but a host process using it.

Check it from the host terminal
- To check which host process is using it execute the command:
```
lsof -i -P -n | grep ":80 (LISTEN)"
```

@dapplion should we type this error and do something specific in response of this? or shoud we just take actions for the HTTPS package since is the more probably to fail due to the port 80 in use?

@dapplion related to the duplicated instances, there were a few naming error in the past with https so it was named: https.https.dnp.dappnode.eth, but that should have been fixed

**Comment by dapplion** [comment] 2021-07-07 08:42
> should we type this error and do something specific in response of this?

Not a bad idea, maybe we should regex the docker error for something more readable

> or shoud we just take actions for the HTTPS package since is the more probably to fail due to the port 80 in use?

It's a bit dangeours since we will always forget about some random edge case. Better to report better and offer options

**Comment by AJolly** [comment] 2021-07-20 05:24
I'm getting the same issue, its the http docker package itself thats grabbing the port.

dappnode@debmain:~$ docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED             STATUS          PORTS                                                                                                                     NAMES
e20de51708c3   dappmanager.dnp.dappnode.eth:0.2.42          "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes                                                                                                                             DAppNodeCore-dappmanager.dnp.dappnode.eth
f700d4c94216   wifi.dnp.dappnode.eth:0.2.7                  "/bin/wlanstart.sh"      24 minutes ago      Up 6 seconds                                                                                                                              DAppNodeCore-wifi.dnp.dappnode.eth
56c59ed53fe2   vpn.dnp.dappnode.eth:0.2.8                   "node src/index"         27 minutes ago      Up 27 minutes   0.0.0.0:1194->1194/udp, :::1194->1194/udp, 0.0.0.0:8092->8092/tcp, :::8092->8092/tcp                                      DAppNodeCore-vpn.dnp.dappnode.eth
0a629b1bdf45   wireguard.wireguard.dnp.dappnode.eth:0.1.0   "/init"                  About an hour ago   Up 53 minutes   0.0.0.0:51820->51820/udp, :::51820->51820/udp                                                                             DAppNodeCore-wireguard.wireguard.dnp.dappnode.eth
7dc5703e3f53   api.wireguard.dnp.dappnode.eth:0.1.0         "node src/index"         About an hour ago   Up 53 minutes                                                                                                                             DAppNodeCore-api.wireguard.dnp.dappnode.eth
061daada9a71   ipfs.dnp.dappnode.eth:0.2.14                 "/sbin/tini -- /usr/…"   About an hour ago   Up 53 minutes   5001/tcp, 4001/udp, 0.0.0.0:4001->4001/tcp, :::4001->4001/tcp, 0.0.0.0:4002->4002/udp, :::4002->4002/udp, 8080-8081/tcp   DAppNodeCore-ipfs.dnp.dappnode.eth
d0285b199615   https.dnp.dappnode.eth:0.1.1                 "/init"                  About an hour ago   Up 53 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                  DAppNodeCore-https.dnp.dappnode.eth
bf32317e7683   bind.dnp.dappnode.eth:0.2.6                  "supervisord"            About an hour ago   Up 53 minutes   53/udp                                                                                                                    DAppNodeCore-bind.dnp.dappnode.eth
dappnode@debmain:~$ lsof -i -P -n | grep ":80 (LISTEN)"
dappnode@debmain:~$ sudo !!
sudo lsof -i -P -n | grep ":80 (LISTEN)"
[sudo] password for dappnode:
dappnode is not in the sudoers file.  This incident will be reported.
dappnode@debmain:~$ su
Password:
root@debmain:/home/dappnode# lsof -i -P -n | grep ":80 (LISTEN)"
docker-pr   1962     root    4u  IPv4  65602      0t0  TCP *:80 (LISTEN)
docker-pr   1970     root    4u  IPv6  46518      0t0  TCP *:80 (LISTEN)
root@debmain:/home/dappnode# docker ps | grep 80
56c59ed53fe2   vpn.dnp.dappnode.eth:0.2.8                   "node src/index"         28 minutes ago      Up 28 minutes   0.0.0.0:1194->1194/udp, :::1194->1194/udp, 0.0.0.0:8092->8092/tcp, :::8092->8092/tcp                                      DAppNodeCore-vpn.dnp.dappnode.eth
061daada9a71   ipfs.dnp.dappnode.eth:0.2.14                 "/sbin/tini -- /usr/…"   About an hour ago   Up 54 minutes   5001/tcp, 4001/udp, 0.0.0.0:4001->4001/tcp, :::4001->4001/tcp, 0.0.0.0:4002->4002/udp, :::4002->4002/udp, 8080-8081/tcp   DAppNodeCore-ipfs.dnp.dappnode.eth
d0285b199615   https.dnp.dappnode.eth:0.1.1                 "/init"                  About an hour ago   Up 54 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                  DAppNodeCore-https.dnp.dappnode.eth
root@debmain:/home/dappnode#



Reply: Error setting LOCAL_PROXYING: ENOENT: no such file or directory, open '/usr/src/app/DNCORE/docker-compose-https.yml'
Error: Error setting LOCAL_PROXYING: ENOENT: no such file or directory, open '/usr/src/app/DNCORE/docker-compose-https.yml'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Function.readFrom (/usr/src/app/webpack:/src/modules/compose/editor.ts:172:27)
    at new ComposeFileEditor (/usr/src/app/webpack:/src/modules/compose/editor.ts:257:25)
    at Object.<anonymous> (/usr/src/app/webpack:/src/calls/packageSetEnvironment.ts:21:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:66678:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

true

**Comment by pablomendezroyo** [comment] 2021-07-22 13:48
> I'm getting the same issue, its the http docker package itself thats grabbing the port.
> 
> dappnode@debmain:~$ docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES e20de51708c3 dappmanager.dnp.dappnode.eth:0.2.42 "docker-entrypoint.s…" 12 minutes ago Up 12 minutes DAppNodeCore-dappmanager.dnp.dappnode.eth f700d4c94216 wifi.dnp.dappnode.eth:0.2.7 "/bin/wlanstart.sh" 24 minutes ago Up 6 seconds DAppNodeCore-wifi.dnp.dappnode.eth 56c59ed53fe2 vpn.dnp.dappnode.eth:0.2.8 "node src/index" 27 minutes ago Up 27 minutes 0.0.0.0:1194->1194/udp, :::1194->1194/udp, 0.0.0.0:8092->8092/tcp, :::8092->8092/tcp DAppNodeCore-vpn.dnp.dappnode.eth 0a629b1bdf45 wireguard.wireguard.dnp.dappnode.eth:0.1.0 "/init" About an hour ago Up 53 minutes 0.0.0.0:51820->51820/udp, :::51820->51820/udp DAppNodeCore-wireguard.wireguard.dnp.dappnode.eth 7dc5703e3f53 api.wireguard.dnp.dappnode.eth:0.1.0 "node src/index" About an hour ago Up 53 minutes DAppNodeCore-api.wireguard.dnp.dappnode.eth 061daada9a71 ipfs.dnp.dappnode.eth:0.2.14 "/sbin/tini -- /usr/…" About an hour ago Up 53 minutes 5001/tcp, 4001/udp, 0.0.0.0:4001->4001/tcp, :::4001->4001/tcp, 0.0.0.0:4002->4002/udp, :::4002->4002/udp, 8080-8081/tcp DAppNodeCore-ipfs.dnp.dappnode.eth d0285b199615 https.dnp.dappnode.eth:0.1.1 "/init" About an hour ago Up 53 minutes 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp DAppNodeCore-https.dnp.dappnode.eth bf32317e7683 bind.dnp.dappnode.eth:0.2.6 "supervisord" About an hour ago Up 53 minutes 53/udp DAppNodeCore-bind.dnp.dappnode.eth dappnode@debmain:~$ lsof -i -P -n | grep ":80 (LISTEN)"
> dappnode@debmain:~$ sudo !! sudo lsof -i -P -n | grep ":80 (LISTEN)" [sudo] password for dappnode: dappnode is not in the sudoers file. This incident will be reported. dappnode@debmain:~$ su
> Password:
> root@debmain:/home/dappnode# lsof -i -P -n | grep ":80 (LISTEN)"
> docker-pr 1962 root 4u IPv4 65602 0t0 TCP *:80 (LISTEN)
> docker-pr 1970 root 4u IPv6 46518 0t0 TCP *:80 (LISTEN)
> root@debmain:/home/dappnode# docker ps | grep 80
> 56c59ed53fe2 vpn.dnp.dappnode.eth:0.2.8 "node src/index" 28 minutes ago Up 28 minutes 0.0.0.0:1194->1194/udp, :::1194->1194/udp, 0.0.0.0:8092->8092/tcp, :::8092->8092/tcp DAppNodeCore-vpn.dnp.dappnode.eth
> 061daada9a71 ipfs.dnp.dappnode.eth:0.2.14 "/sbin/tini -- /usr/…" About an hour ago Up 54 minutes 5001/tcp, 4001/udp, 0.0.0.0:4001->4001/tcp, :::4001->4001/tcp, 0.0.0.0:4002->4002/udp, :::4002->4002/udp, 8080-8081/tcp DAppNodeCore-ipfs.dnp.dappnode.eth
> d0285b199615 https.dnp.dappnode.eth:0.1.1 "/init" About an hour ago Up 54 minutes 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp DAppNodeCore-https.dnp.dappnode.eth
> root@debmain:/home/dappnode#
> 
> Reply: Error setting LOCAL_PROXYING: ENOENT: no such file or directory, open '/usr/src/app/DNCORE/docker-compose-https.yml'
> Error: Error setting LOCAL_PROXYING: ENOENT: no such file or directory, open '/usr/src/app/DNCORE/docker-compose-https.yml'
> at Object.openSync (fs.js:462:3)
> at Object.readFileSync (fs.js:364:35)
> at Function.readFrom (/usr/src/app/webpack:/src/modules/compose/editor.ts:172:27)
> at new ComposeFileEditor (/usr/src/app/webpack:/src/modules/compose/editor.ts:257:25)
> at Object. (/usr/src/app/webpack:/src/calls/packageSetEnvironment.ts:21:19)
> at Generator.next ()
> at fulfilled (/usr/src/app/index.js:66678:58)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> true

This issue is already addressed here https://github.com/dappnode/DNP_DAPPMANAGER/issues/822

**Comment by pablomendezroyo** [comment] 2021-07-22 13:48
closed by https://github.com/dappnode/DNP_DAPPMANAGER/issues/851

**Closed by pablomendezroyo** 2021-07-22 13:48 UTC
